#!/usr/bin/env ruby
require 'sekisho'
require 'yaml'
require 'date'
require 'logger'

def repositories
  yaml = YAML.load_file('github_repositories.yml')
  return yaml['repository']
end

cm = Sekisho::Milestone.new

THURSDAY_WDAY = 4

target_milestones = []
for i in 0..3 do
  target_milestones << cm.get_next_week(Date.today.next_day(i * 7), THURSDAY_WDAY)
end

repositories.each do |repo|
  logger.info("repository: #{repo}")
  open_milestones = []
  cm.list_milestones(repo).each do |mile|
    begin
      open_milestones << Date.strptime(mile[:title])
    rescue
      next
    end
  end

  (target_milestones - open_milestones).each do |mile|
    cm.create_milestone(repo, mile)
  end
end
